version: 2

sources:
  - name: vegaprod
    database: d8-warehouse
    schema: vegaprod
    description: Base de données de l'entreprise alimentée par l'ERP VEGA.

    tables:
      - name: CTBCONT
        loaded_at_field: _airbyte_extracted_at
        description: Table des sièges sociaux de l'entreprise. Le code siège social se retrouve un peu partout au niveau des tables mais pas autant que le code PDV.
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour

      - name: CLIENTI
        loaded_at_field: _airbyte_extracted_at
        description: Liste des sites. Chaque siège social dispose d'un ou plusieurs sites. On peut assimiler ça à des filiales.

      - name: CHIAMATE
        loaded_at_field: _airbyte_extracted_at
        description: Table des appels comprenant des liens vers d'autres tables comme les points de ventes (UNOPV) et les sièges sociaux (CTBCONT)
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour

      - name: AGENTI
        loaded_at_field: _airbyte_extracted_at
        description: Table du personnel D8.

      - name: FATTURE
        loaded_at_field: _airbyte_extracted_at
        description: Table des factures de l'entreprise.

      - name: FATRIG
        loaded_at_field: _airbyte_extracted_at
        description: Détails des factures.

      - name: NOTECREDITO
        loaded_at_field: _airbyte_extracted_at
        description: Table des avoirs de l'entreprise.
      
      - name: RIGHENOTECREDITO
        loaded_at_field: _airbyte_extracted_at
        description: Détails de la table des avoirs de l'entreprise.

      - name: GIRIAGENTI
        loaded_at_field: _airbyte_extracted_at
        description: Passages par PDV par E.C.R.D

      - name: PASDST
        loaded_at_field: _airbyte_extracted_at
        description: Table contenant la liste des passages des opérateurs auprès d'un Point De Vente.

      - name: DETRIF
        loaded_at_field: _airbyte_extracted_at
        description: Table contenant les informations des ravitaillements.

      - name: RIGRIF
        loaded_at_field: _airbyte_extrated_at
        description: Table contenant le détails des produits livrés pendant le ravitaillement.

      - name: MODELLI
        loaded_at_field: _airbyte_extracted_at
        description: Modèles DA

      - name: UNOPV
        loaded_at_field: _airbyte_extracted_at
        description: Liste des Points De Vente (PDV) de l'entreprise

      - name: BPCUSTOMER
        loaded_at_field: _airbyte_extracted_at
        description: Tables des clients VEGA dans la base de données du logiciel de comptabilité Sage X3.
        freshness:
          warn_after:
            count: 1
            period: hour
          error_after:
            count: 24
            period: hour
